[flavor]
dark = "catppuccin-mocha"

[icon]
dirs  = [ 
	{ name = ".config", text = "" }, 
 	{ name = "Área de trabalho", text = "" }, 
 	{ name = "Projetos", text = "" }, 
 	{ name = "Documentos", text = "" }, 
 	{ name = "Downloads", text = "" }, 
 	{ name = "Modelos", text = "" },  
 	{ name = "Músicas", text = "" }, 
 	{ name = "Imagens", text = "" }, 
 	{ name = "Público", text = "" }, 
 	{ name = "Vídeos", text = "" },
	{ name = "Git", text = "" }, 
 ] 
